name: CI
on: pull_request

jobs:
  filter:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    outputs:
      ci-needed: ${{ steps.filter.outputs.ci-needed }}
    steps:
      - id: filter
        name: Check changed files
        uses: dorny/paths-filter@v3
        with:
          filters: |
            ci-needed:
              - '**.py'
              - 'pyproject.toml'
              - 'uv.lock'
              - '.github/workflows/ci.yaml'

  ci:
    needs: filter
    if: ${{ needs.filter.outputs.ci-needed == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: |
          echo Running tests...
          sleep 5
          exit 1

  dependabot-auto-merge:
    needs: ci
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Auto-merge Dependabot PRs
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr merge --auto --merge "$PR_URL"
